services:
  postgres:
    container_name: pg_uuidv7
    build:
      context: .
    ports:
      - 28801:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U postgres" ]
      interval: 1s
      timeout: 10s
      retries: 5
